import { Router } from "express";
import authorizeRoles from "../middlewares/authorizeRoles.js";
import { getAllCertificates, getCertificateById, createCertificate, updateCertificate, deleteCertificate } from "../controllers/certificateController.js";
const router = Router();
router.get("/allcertificates",authorizeRoles('admin'), getAllCertificates);
router.get("/certificatebyid/:id", getCertificateById);
router.post("/addcertificate",authorizeRoles('admin'), createCertificate);
router.put("/updatecertificate/:id",authorizeRoles('admin'), updateCertificate);
router.delete("/deletecertificate/:id", authorizeRoles('admin'),deleteCertificate);
export default router;