import { Router } from "express";
const router = Router();
import authorizeRoles from "../middlewares/authorizeRoles.js";
import { getEvents, getEventById, createEvent, updateEvent, deleteEvent } from "../controllers/eventController.js";   
router.get("/allevents", getEvents);
router.get("/eventbyid/:id", getEventById); 
router.post("/addevent", authorizeRoles('admin'), createEvent);
router.put("/updateevent/:id" , authorizeRoles('admin'), updateEvent);  
router.delete("/deleteevent/:id", authorizeRoles('admin'), deleteEvent);
export default router;
