import { Router } from "express";
import authorizeRoles from "../middlewares/authorizeRoles.js";
const router = Router();
import { getRegistrations, getRegistrationById, createRegistration, updateRegistration, deleteRegistration } from "../controllers/registrationController.js";
router.get("/allregistrations",authorizeRoles('admin'), getRegistrations);
router.get("/registrationbyid/:id", getRegistrationById);
router.post("/addregistration", createRegistration);
router.put("/updateregistration/:id",authorizeRoles('admin'), updateRegistration);
router.delete("/deleteregistration/:id",authorizeRoles('admin'), deleteRegistration);
export default router;