import { Router } from "express";
import authorizeRoles from "../middlewares/authorizeRoles.js";
const router = Router();
import { getRegistrations, getRegistrationById, createRegistration, updateRegistration, deleteRegistration } from "../controllers/registrationController.js";
router.get("/allregistrations",authorizeRoles('admin'), getRegistrations);
router.get("/registration/:id", getRegistrationById);
router.post("/registration", createRegistration);
router.put("/registration/:id",authorizeRoles('admin'), updateRegistration);
router.delete("/registration/:id",authorizeRoles('admin'), deleteRegistration);
export default router;