import { Router } from "express";
import authorizeRoles from "../middlewares/authorizeRoles.js";
import { getTopics, getTopicById, createTopic, updateTopic, deleteTopic } from "../controllers/topicController.js"; 
const router = Router();
router.get("/alltopics", getTopics);
router.get("/topic/:id", getTopicById);
router.post("/topic",authorizeRoles('admin'), createTopic);
router.put("/topic/:id",authorizeRoles('admin'), updateTopic);
router.delete("/topic/:id", authorizeRoles('admin'), deleteTopic);
export default router;