import { Router } from "express";
import authorizeRoles from "../middlewares/authorizeRoles.js";
import { getTopics, getTopicById, createTopic, updateTopic, deleteTopic } from "../controllers/topicController.js"; 
const router = Router();
router.get("/alltopics", getTopics);
router.get("/topicbyid/:id", getTopicById);
router.post("/addtopic",authorizeRoles('admin'), createTopic);
router.put("/updatetopic/:id",authorizeRoles('admin'), updateTopic);
router.delete("/deletetopic/:id", authorizeRoles('admin'), deleteTopic);
export default router;