import { Router } from "express";
// import authenticateToken from "../middlewares/authenticateToken.js";
import authorizeRoles from "../middlewares/authorizeRoles.js";
import { getUsers ,getUserById,createUser,updateUser,deleteUser} from "../controllers/userController.js";
const router = Router();
router.get("/allusers",authorizeRoles('admin'), getUsers);
router.get("/userbyid/:id", getUserById);
router.post("/adduser", createUser);  
router.put("/updateuser/:id",authorizeRoles('admin'), updateUser);
router.delete("/deleteuser/:id",authorizeRoles('admin'), deleteUser);
export default router;
