import { Router } from "express";
// import authenticateToken from "../middlewares/authenticateToken.js";
import authorizeRoles from "../middlewares/authorizeRoles.js";
import { getUsers ,getUserById,createUser,updateUser,deleteUser} from "../controllers/userController.js";
const router = Router();
router.use(authorizeRoles('admin'));
router.get("/allusers", getUsers);
router.post("/adduser", createUser);  
router.get("/userbyid/:id", getUserById);
router.put("/updateuser/:id", updateUser);
router.delete("/deleteuser/:id", deleteUser);
export default router;
